version: 0.1

environment_variables:
  plaintext:
    REPO_NAME: "grfn-ingest-step-function"
    PIPELINE_NAME: "ingest-step-function"
phases:
  build:
    commands:
      - aws codepipeline get-pipeline-state --name $PIPELINE_NAME --query 'stageStates[*].actionStates[?actionName==`Source`].currentRevision.revisionId' --output text | cut -c1-7 > sha1.txt
      - aws stepfunctions create-state-machine -name grfn-ingest-$(cat sha1.txt) --definition $(cat step-function.json) --role-arn arn:aws:iam::406893895021:role/service-role/StatesExecutionRole-us-east-1
