version: 0.1

environment_variables:
  plaintext:
    BUCKET: "grfn-software"
    PREFIX: "lambda"
    IMAGE_NAME: "ingest"
    IMAGE_HOST: "406893895021.dkr.ecr.us-east-1.amazonaws.com"
    MATURITY: "PROD"
    SHA1: "c97cce3"

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - docker pull $IMAGE_HOST/$IMAGE_NAME:$SHA1
      - docker tag $IMAGE_HOST/$IMAGE_NAME:$SHA1 $IMAGE_HOST/$IMAGE_NAME:$MATURITY
      - pip install -r invoke/requirements.txt -t invoke/src/
      - pip install -r verify/requirements.txt -t verify/src/
      - pip install -r notify/requirements.txt -t notify/src/
      - pip install -r metrics/requirements.txt -t metrics/src/
      - pip install -r echo10-to-cmr/requirements.txt -t echo10-to-cmr/src/
      - apt-get update
      - apt-get install -y libgeos-dev
      - mkdir echo10-construction/src/lib
      - cp -L /usr/lib/libgeos*.so* echo10-construction/src/lib/
      - pip install -r echo10-construction/requirements.txt -t echo10-construction/src/
      - aws cloudformation package --template-file cloudformation-wrapper.yaml --s3-bucket $BUCKET --s3-prefix $PREFIX --output-template-file cloudformation-final.yaml
  post_build:
    commands:
      - docker push $IMAGE_HOST/$IMAGE_NAME:$MATURITY
artifacts:
  type: zip
  files:
    - cloudformation-final.yaml
