# This build script is designed to run in AWS CodeBuild using the aws/codebuild/docker:17.09.0 image:
#   ubuntu 14.04.5
#   docker 17.09.0
#   python 2.7

version: 0.1

phases:
  build:
    commands:
      - pip install -r invoke/requirements.txt -t invoke/src/
      - pip install -r verify/requirements.txt -t verify/src/
      - pip install -r ingest/requirements.txt -t ingest/src/
      - pip install -r notify/requirements.txt -t notify/src/
      - pip install -r cmr-token/requirements.txt -t cmr-token/src/
      - pip install -r echo10-to-cmr/requirements.txt -t echo10-to-cmr/src/
      - apt-get update
      - apt-get install -y libgeos-dev
      - mkdir echo10-construction/src/lib
      - cp -L /usr/lib/libgeos*.so* echo10-construction/src/lib/
      - pip install -r echo10-construction/requirements.txt -t echo10-construction/src/
      - aws cloudformation package --template-file cloudformation.yaml --s3-bucket $BUCKET --s3-prefix $PREFIX --output-template-file cloudformation-final.yaml
artifacts:
  type: zip
  files:
    - cloudformation-final.yaml
