version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - apt update
      - apt install -y libgeos-dev
  build:
    commands:
      - pip3 install -r invoke/requirements.txt -t invoke/src/
      - pip3 install -r verify/requirements.txt -t verify/src/
      - pip3 install -r ingest/requirements.txt -t ingest/src/
      - pip3 install -r notify/requirements.txt -t notify/src/
      - pip3 install -r cmr-token/requirements.txt -t cmr-token/src/
      - pip3 install -r echo10-to-cmr/requirements.txt -t echo10-to-cmr/src/
      - mkdir echo10-construction/src/lib
      - cp -L /usr/lib/libgeos*.so* echo10-construction/src/lib/
      - pip3 install -r echo10-construction/requirements.txt -t echo10-construction/src/
      - aws cloudformation package --template-file cloudformation.yaml --s3-bucket $BUCKET --s3-prefix $PREFIX --output-template-file cloudformation-final.yaml
artifacts:
  type: zip
  files:
    - cloudformation-final.yaml
