version: 0.1

environment_variables:
  plaintext:
    STEP_FUNCTION_NAME: "grfn-ingest"
    MATURITY: "TEST"
    REPO_NAME: "grfn-ingest-step-function"
    PIPELINE_NAME: "grfn-ingest-step-function-test"
    ROLE_ARN: "arn:aws:iam::406893895021:role/service-role/StatesExecutionRole-us-east-1"
phases:
  pre_build:
    commands:
      - aws codepipeline get-pipeline-state --name $PIPELINE_NAME --query 'stageStates[*].actionStates[?actionName==`Source`].currentRevision.revisionId' --output text | cut -c1-7 > sha1.txt
      - sed -i "s/\$MATURITY/$MATURITY/" step-function.json
  build:
    commands:
      - aws stepfunctions create-state-machine --name $STEP_FUNCTION_NAME-$MATURITY-$(date +%s)-$(cat sha1.txt) --definition file://step-function.json --role-arn $ROLE_ARN
