AWSTemplateFormatVersion: 2010-09-09

Parameters:

  LogLevel:
    Type: String
    Default: INFO
    AllowedValues:
    - CRITICAL
    - ERROR
    - WARNING
    - INFO
    - DEBUG

  OregonTopicArn:
    Description: ARN of ingest topic in us-west-2.  Can be removed when we fix JPL access.
    Type: String
    Default: arn:aws:sns:us-west-2:765666652335:grfn-archive-test

Resources:

  StepFunctionStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Ref AWS::StackName
        VerifyLambdaArn: !GetAtt VerifyStack.Outputs.LambdaArn
        NotifyLambdaArn: arn:aws:lambda:us-east-1:406893895021:function:notify:TEST
        Echo10ConstructionLambdaArn: arn:aws:lambda:us-east-1:406893895021:function:echo10-construction:TEST
      TemplateURL: step-function/cloudformation.yaml

  InvokeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Sub "${AWS::StackName}-invoke"
        LogLevel: !Ref LogLevel
        QueueUrl: !Ref JobQueue
        QueueArn: !GetAtt JobQueue.Arn
        StepFunctionArn: !GetAtt StepFunctionStack.Outputs.StepFunctionArn
      TemplateURL: invoke/cloudformation.yaml

  VerifyStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Sub "${AWS::StackName}-verify"
        LogLevel: !Ref LogLevel
      TemplateURL: verify/cloudformation.yaml

  ErrorTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${AWS::StackName}-errors"

  ErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AWS::StackName}-errors"
      AlarmDescription: Ingest failure alarm
      AlarmActions:
        - !Ref ErrorTopic
      Dimensions:
        - Name: StateMachineArn
          Value: !GetAtt StepFunctionStack.Outputs.StepFunctionArn
      MetricName: ExecutionsFailed
      Namespace: AWS/States
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      Period: 300
      Statistic: Sum
      Threshold: 1
      Unit: Count
      TreatMissingData: notBreaching

  JobQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AWS::StackName}-jobs"
      MessageRetentionPeriod: 1209600
      VisibilityTimeout: 10

  JobTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${AWS::StackName}-jobs"
      Subscription:
      - Protocol: sqs
        Endpoint: !GetAtt JobQueue.Arn

  JobQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument: !Sub |-
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": "*",
              "Resource": "${JobQueue.Arn}",
              "Action": "sqs:SendMessage",
              "Condition": {
                "ArnEquals": {
                  "aws:SourceArn": "${JobTopic}"
                }
              }
            },
            {
              "Effect": "Allow",
              "Principal": "*",
              "Resource": "${JobQueue.Arn}",
              "Action": "sqs:SendMessage",
              "Condition": {
                "ArnEquals": {
                  "aws:SourceArn": "${OregonTopicArn}"
                }
              }
            }
          ]
        }
      Queues:
      - !Ref JobQueue
