AWSTemplateFormatVersion: 2010-09-09

Parameters:

  LogLevel:
    Type: String
    Default: INFO
    AllowedValues:
    - CRITICAL
    - ERROR
    - WARNING
    - INFO
    - DEBUG

  PrivateBucket:
    Type: String
    Default: grfn-private-test

  PublicBucket:
    Type: String
    Default: grfn-public-test

  DistributionBaseUrl:
    Type: String
    Default: https://grfn-test.asf.alaska.edu/door/download

  BrowseBaseUrl:
    Type: String
    Default: https://grfn-public-test.asf.alaska.edu

  DefaultResponseTopicArn:
    Type: String
    Default: arn:aws:sns:us-east-1:406893895021:success-test

  DefaultResponseTopicRegion:
    Type: String
    Default: us-east-1
    AllowedValues:
    - us-east-2
    - us-east-1
    - us-west-1
    - us-west-2
    - ap-south-1
    - ap-northeast-2
    - ap-southeast-1
    - ap-southeast-2
    - ap-northeast-1
    - ca-central-1
    - cn-north-1
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - eu-west-3
    - sa-east-1

  OregonTopicArn:
    Description: ARN of ingest topic in us-west-2.  Can be removed when we fix JPL access.
    Type: String
    Default: arn:aws:sns:us-west-2:765666652335:grfn-archive-test

  CachedCmrTokenBucket:
    Type: String
    Default: grfn-echo10-test

  CachedCmrTokenKey:
    Type: String
    Default: cached-cmr-auth-token-test

  CmrTokenLambda:
    Type: String
    Default: cmr-token:TEST

  CmrGranuleUrl:
    Type: String
    Default: https://cmr.uat.earthdata.nasa.gov/ingest/providers/ASF/granules/

  IngestContainerImage:
    Type: String
    Default: 406893895021.dkr.ecr.us-east-1.amazonaws.com/ingest:TEST

  IngestEc2Timeout:
    Type: Number
    MinValue: 0
    Default: 300

  IngestActivityTimeout:
    Type: Number
    MinValue: 0
    Default: 600

  Name:
    Type: String
    Default: NotSet

Outputs:

  JobTopic:
    Value: !Ref JobTopic

  ErrorTopic:
    Value: !Ref ErrorTopic

Resources:

  StepFunctionStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Ref Name
        VerifyLambdaArn: !GetAtt VerifyStack.Outputs.LambdaArn
        NotifyLambdaArn: !GetAtt NotifyStack.Outputs.LambdaArn
        Echo10ConstructionLambdaArn: !GetAtt Echo10ConstructionStack.Outputs.LambdaArn
        IngestActivityTimeout: !Ref IngestActivityTimeout
      TemplateURL: step-function/cloudformation.yaml

  InvokeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Sub "${Name}-invoke"
        LogLevel: !Ref LogLevel
        QueueUrl: !Ref JobQueue
        QueueArn: !GetAtt JobQueue.Arn
        StepFunctionArn: !GetAtt StepFunctionStack.Outputs.StepFunctionArn
      TemplateURL: invoke/cloudformation.yaml

  VerifyStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Sub "${Name}-verify"
        LogLevel: !Ref LogLevel
      TemplateURL: verify/cloudformation.yaml

  Echo10ConstructionStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Sub "${Name}-echo10-construction"
        LogLevel: !Ref LogLevel
        PrivateBucket: !Ref PrivateBucket
        PublicBucket: !Ref PublicBucket
        AuxBucket: !Ref AuxBucket
        DistributionBaseUrl: !Ref DistributionBaseUrl
        BrowseBaseUrl: !Ref BrowseBaseUrl
      TemplateURL: echo10-construction/cloudformation.yaml

  Echo10ToCmrStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Sub "${Name}-echo10-to-cmr"
        LogLevel: !Ref LogLevel
        ActivityArn: !GetAtt StepFunctionStack.Outputs.CmrActivityArn
        AuxBucket: !Ref AuxBucket
        CachedCmrTokenBucket: !Ref CachedCmrTokenBucket
        CachedCmrTokenKey: !Ref CachedCmrTokenKey
        CmrTokenLambda: !Ref CmrTokenLambda
        CmrGranuleUrl: !Ref CmrGranuleUrl
      TemplateURL: echo10-to-cmr/cloudformation.yaml

  NotifyStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Sub "${Name}-notify"
        DefaultResponseTopicArn: !Ref DefaultResponseTopicArn
        DefaultResponseTopicRegion: !Ref DefaultResponseTopicRegion
      TemplateURL: notify/cloudformation.yaml

  MetricsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Sub "${Name}-metrics"
        LogLevel: !Ref LogLevel
        StepFunctionArn: !GetAtt StepFunctionStack.Outputs.StepFunctionArn
      TemplateURL: metrics/cloudformation.yaml

  IngestStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Name: !Sub "${Name}-ingest"
        LogLevel: !Ref LogLevel
        ContainerImage: !Ref IngestContainerImage
        MetricName: !GetAtt MetricsStack.Outputs.MetricName
        MetricNamespace: !GetAtt MetricsStack.Outputs.Namespace
        ActivityArn: !GetAtt StepFunctionStack.Outputs.IngestActivityArn
        PublicBucket: !Ref PublicBucket
        PrivateBucket: !Ref PrivateBucket
        AuxBucket: !Ref AuxBucket
        IngestEc2Timeout: !Ref IngestEc2Timeout
      TemplateURL: ingest/cloudformation.yaml

  AuxBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${Name}-aux"

  ErrorTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${Name}-errors"

  ErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${Name}-errors"
      AlarmDescription: Ingest failure alarm
      AlarmActions:
        - !Ref ErrorTopic
      Dimensions:
        - Name: StateMachineArn
          Value: !GetAtt StepFunctionStack.Outputs.StepFunctionArn
      MetricName: ExecutionsFailed
      Namespace: AWS/States
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      Period: 300
      Statistic: Sum
      Threshold: 1
      Unit: Count
      TreatMissingData: notBreaching

  JobQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${Name}-jobs"
      MessageRetentionPeriod: 1209600
      VisibilityTimeout: 10

  JobTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${Name}-jobs"
      Subscription:
      - Protocol: sqs
        Endpoint: !GetAtt JobQueue.Arn

  JobQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument: !Sub |-
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": "*",
              "Resource": "${JobQueue.Arn}",
              "Action": "sqs:SendMessage",
              "Condition": {
                "ArnEquals": {
                  "aws:SourceArn": "${JobTopic}"
                }
              }
            },
            {
              "Effect": "Allow",
              "Principal": "*",
              "Resource": "${JobQueue.Arn}",
              "Action": "sqs:SendMessage",
              "Condition": {
                "ArnEquals": {
                  "aws:SourceArn": "${OregonTopicArn}"
                }
              }
            }
          ]
        }
      Queues:
      - !Ref JobQueue
