AWSTemplateFormatVersion: 2010-09-09

Parameters:

  LogLevel:
    Type: String
    Default: INFO
    AllowedValues:
    - CRITICAL
    - ERROR
    - WARNING
    - INFO
    - DEBUG

  PrivateBucket:
    Type: String
    Default: grfn-private-test

  PublicBucket:
    Type: String
    Default: grfn-public-test

  DistributionBaseUrl:
    Type: String
    Default: https://grfn-test.asf.alaska.edu/door/download

  BrowseBaseUrl:
    Type: String
    Default: https://grfn-public-test.asf.alaska.edu

  DefaultResponseTopicArn:
    Type: String
    Default: arn:aws:sns:us-east-1:406893895021:success-test

  DefaultResponseTopicRegion:
    Type: String
    Default: us-east-1
    AllowedValues:
    - us-east-2
    - us-east-1
    - us-west-1
    - us-west-2
    - ap-south-1
    - ap-northeast-2
    - ap-southeast-1
    - ap-southeast-2
    - ap-northeast-1
    - ca-central-1
    - cn-north-1
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - eu-west-3
    - sa-east-1

  OregonTopicArn:
    Description: ARN of ingest topic in us-west-2.  Can be removed when we fix JPL access.
    Type: String
    Default: arn:aws:sns:us-west-2:765666652335:grfn-archive-test

  CachedCmrTokenBucket:
    Type: String
    Default: grfn-echo10-test

  CachedCmrTokenKey:
    Type: String
    Default: cached-cmr-auth-token-test

  CmrTokenLambda:
    Type: String
    Default: cmr-token:TEST

  CmrGranuleUrl:
    Type: String
    Default: https://cmr.uat.earthdata.nasa.gov/ingest/providers/ASF/granules/

  IngestContainerImage:
    Type: String
    Default: 406893895021.dkr.ecr.us-east-1.amazonaws.com/ingest:TEST

  IngestEc2Timeout:
    Type: Number
    MinValue: 0
    Default: 300

  Maturity:
    Type: String
    Default: DEV
    AllowedValues:
      - TEST
      - PROD
      - DEV

Resources:

  MainStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
        - Key: MATURITY
          Value: !Ref Maturity
        - Key: APPLICATION
          Value: GRFN-INGEST
      Parameters:
        Name: !Ref AWS::StackName
        LogLevel: !Ref LogLevel
        PrivateBucket: !Ref PrivateBucket
        PublicBucket: !Ref PublicBucket
        DistributionBaseUrl: !Ref DistributionBaseUrl
        BrowseBaseUrl: !Ref BrowseBaseUrl
        CachedCmrTokenBucket: !Ref CachedCmrTokenBucket
        CachedCmrTokenKey: !Ref CachedCmrTokenKey
        CmrTokenLambda: !Ref CmrTokenLambda
        CmrGranuleUrl: !Ref CmrGranuleUrl
        DefaultResponseTopicArn: !Ref DefaultResponseTopicArn
        DefaultResponseTopicRegion: !Ref DefaultResponseTopicRegion
        IngestContainerImage: !Ref IngestContainerImage
        IngestEc2Timeout: !Ref IngestEc2Timeout
        OregonTopicArn: !Ref OregonTopicArn
      TemplateURL: cloudformation-main.yaml
