AWSTemplateFormatVersion: 2010-09-09

Parameters:

  PrivateBucket:
    Description: Name of S3 bucket in which zipped output products will be archived
    Type: String

  PublicBucket:
    Description: Name of S3 bucket in which browse images will be archived
    Type: String

  DistributionBaseUrl:
    Description: Base URL for product distribution, e.g. http://foo.com will generate download URLs of http://foo.com/<product-file-name>
    Type: String

  BrowseBaseUrl:
    Description: Base URL for browse images, e.g. http://foo.com will generate browse image URLs of http://foo.com/<browse-file-name>
    Type: String

  ReformatApiUrl:
    Description: Url endpoint for downloading geotiff versions of products, e.g. https://services.asf.alaska.edu/geospatial/reformat
    Type: String

  DefaultResponseTopicArn:
    Description: SNS topic arn where error/success responses will be sent for jobs where no response topic is specified
    Type: String

  DefaultResponseTopicRegion:
    Description: AWS region of the topic specified for DefaultResponseTopicArn
    Type: String
    Default: us-east-1
    AllowedValues:
    - us-east-2
    - us-east-1
    - us-west-1
    - us-west-2
    - ap-south-1
    - ap-northeast-2
    - ap-southeast-1
    - ap-southeast-2
    - ap-northeast-1
    - ca-central-1
    - cn-north-1
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - eu-west-3
    - sa-east-1

  SdsAccountNumber:
    Description: AWS Account Number for the SDS that will be publishing messages to the ingest job topic
    Type: Number

  CmrBaseUrl:
    Description: Base URL of the CMR deployment to integrate with
    Type: String
    Default: https://cmr.uat.earthdata.nasa.gov
    AllowedValues:
    - https://cmr.earthdata.nasa.gov
    - https://cmr.uat.earthdata.nasa.gov

  CmrUsername:
    Type: String

  CmrPassword:
    Type: String
    NoEcho: true

  CmrProvider:
    Description: Provider value to use when ingesting products into CMR
    Type: String

  CmrClientId:
    Description: Value for Client-Id header included with CMR search requests
    Type: String

  Maturity:
    Description: Value for MATURITY tag to be applied to all taggable resources
    Type: String
    Default: DEV
    AllowedValues:
    - PROD
    - TEST
    - DEV

Outputs:

  JobTopic:
    Description: Submit ingest jobs to this topic
    Value: !GetAtt MainStack.Outputs.JobTopic

  ErrorTopic:
    Description: Subscribe to this topic to receive a notification when one or more ingest jobs fail
    Value: !GetAtt MainStack.Outputs.ErrorTopic

Resources:

  MainStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
      - Key: MATURITY
        Value: !Ref Maturity
      - Key: APPLICATION
        Value: GRFN-INGEST
      Parameters:
        Name: !Ref AWS::StackName
        PrivateBucket: !Ref PrivateBucket
        PublicBucket: !Ref PublicBucket
        DistributionBaseUrl: !Ref DistributionBaseUrl
        BrowseBaseUrl: !Ref BrowseBaseUrl
        ReformatApiUrl: !Ref ReformatApiUrl
        DefaultResponseTopicArn: !Ref DefaultResponseTopicArn
        DefaultResponseTopicRegion: !Ref DefaultResponseTopicRegion
        SdsAccountNumber: !Ref SdsAccountNumber
        CmrBaseUrl: !Ref CmrBaseUrl
        CmrUsername: !Ref CmrUsername
        CmrPassword: !Ref CmrPassword
        CmrProvider: !Ref CmrProvider
        CmrClientId: !Ref CmrClientId
      TemplateURL: cloudformation-main.yaml
