AWSTemplateFormatVersion: 2010-09-09

Parameters:

  LogLevel:
    Description: Application logging level
    Type: String
    Default: INFO
    AllowedValues:
    - CRITICAL
    - ERROR
    - WARNING
    - INFO
    - DEBUG

  PrivateBucket:
    Description: Name of S3 bucket in which zipped output products will be archived
    Type: String
    Default: grfn-private-test

  PublicBucket:
    Description: Name of S3 bucket in which browse images will be archived
    Type: String
    Default: grfn-public-test

  DistributionBaseUrl:
    Description: Base URL for product distribution, e.g. http://foo.com will generate download URLs of http://foo.com/<product-file-name>
    Type: String
    Default: https://grfn-test.asf.alaska.edu/door/download

  BrowseBaseUrl:
    Description: Base URL for browse images, e.g. http://foo.com will generate browse image URLs of http://foo.com/<browse-file-name>
    Type: String
    Default: https://grfn-public-test.asf.alaska.edu

  DefaultResponseTopicArn:
    Description: SNS topic arn where error/success responses will be sent for each product
    Type: String
    Default: arn:aws:sns:us-east-1:406893895021:success-test

  DefaultResponseTopicRegion:
    Description: AWS region for the topic specified for DefaultResponseTopicArn
    Type: String
    Default: us-east-1
    AllowedValues:
    - us-east-2
    - us-east-1
    - us-west-1
    - us-west-2
    - ap-south-1
    - ap-northeast-2
    - ap-southeast-1
    - ap-southeast-2
    - ap-northeast-1
    - ca-central-1
    - cn-north-1
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - eu-west-3
    - sa-east-1

  OregonTopicArn:
    Description: ARN of ingest topic in us-west-2.  Can be removed when we fix JPL access.
    Type: String
    Default: arn:aws:sns:us-west-2:765666652335:grfn-archive-test

  CachedCmrTokenBucket:
    Description: Name of S3 bucket where cached CMR authentication token is stored
    Type: String
    Default: grfn-echo10-test

  CachedCmrTokenKey:
    Description: S3 key where cached CMR authentication token is stored
    Type: String
    Default: cached-cmr-auth-token-test

  CmrTokenLambda:
    Description: Name of lambda function for fetching new CMR authentication tokens
    Type: String
    Default: cmr-token:TEST

  CmrGranuleUrl:
    Description: Base URL for the CMR Create/Update granule endpoint
    Type: String
    Default: https://cmr.uat.earthdata.nasa.gov/ingest/providers/ASF/granules/

  IngestContainerImage:
    Description: Full URL path of the docker container image to use for ingest activities
    Type: String
    Default: 406893895021.dkr.ecr.us-east-1.amazonaws.com/ingest:TEST

  IngestEc2Timeout:
    Description: Duration of EC2 autoscaling lifecycle termination hook, in seconds
    Type: Number
    MinValue: 0
    Default: 300

  IngestActivityTimeout:
    Description: Timeout for step function ingest activity, in seconds
    Type: Number
    MinValue: 0
    Default: 600

  Maturity:
    Description: Value for MATURITY tag to be applied to all taggable resources
    Type: String
    Default: DEV
    AllowedValues:
      - TEST
      - PROD
      - DEV

Outputs:

  JobTopic:
    Description: Submit ingest jobs to this topic
    Value: !GetAtt MainStack.Outputs.JobTopic

  ErrorTopic:
    Description: Subscribe to this topic to receive a notification when one or more ingest jobs fail
    Value: !GetAtt MainStack.Outputs.ErrorTopic

Resources:

  MainStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
        - Key: MATURITY
          Value: !Ref Maturity
        - Key: APPLICATION
          Value: GRFN-INGEST
      Parameters:
        Name: !Ref AWS::StackName
        LogLevel: !Ref LogLevel
        PrivateBucket: !Ref PrivateBucket
        PublicBucket: !Ref PublicBucket
        DistributionBaseUrl: !Ref DistributionBaseUrl
        BrowseBaseUrl: !Ref BrowseBaseUrl
        CachedCmrTokenBucket: !Ref CachedCmrTokenBucket
        CachedCmrTokenKey: !Ref CachedCmrTokenKey
        CmrTokenLambda: !Ref CmrTokenLambda
        CmrGranuleUrl: !Ref CmrGranuleUrl
        DefaultResponseTopicArn: !Ref DefaultResponseTopicArn
        DefaultResponseTopicRegion: !Ref DefaultResponseTopicRegion
        IngestContainerImage: !Ref IngestContainerImage
        IngestEc2Timeout: !Ref IngestEc2Timeout
        IngestActivityTimeout: !Ref IngestActivityTimeout
        OregonTopicArn: !Ref OregonTopicArn
      TemplateURL: cloudformation-main.yaml
