AWSTemplateFormatVersion: 2010-09-09

Parameters:

  LogLevel:
    Description: Application logging level
    Type: String
    Default: INFO
    AllowedValues:
    - CRITICAL
    - ERROR
    - WARNING
    - INFO
    - DEBUG

  VpcId:
    Description: VPC Id in which to launch EC2 instances for ingest activities
    Type: AWS::EC2::VPC::Id

  SubnetId:
    Description: List of Subnet Ids in which to launch EC2 instances for ingest activities
    Type: List<AWS::EC2::Subnet::Id>

  PrivateBucket:
    Description: Name of S3 bucket in which zipped output products will be archived
    Type: String

  PublicBucket:
    Description: Name of S3 bucket in which browse images will be archived
    Type: String

  DistributionBaseUrl:
    Description: Base URL for product distribution, e.g. http://foo.com will generate download URLs of http://foo.com/<product-file-name>
    Type: String

  BrowseBaseUrl:
    Description: Base URL for browse images, e.g. http://foo.com will generate browse image URLs of http://foo.com/<browse-file-name>
    Type: String

  DefaultResponseTopicArn:
    Description: SNS topic arn where error/success responses will be sent for jobs where no response topic is specified
    Type: String

  DefaultResponseTopicRegion:
    Description: AWS region of the topic specified for DefaultResponseTopicArn
    Type: String
    Default: us-east-1
    AllowedValues:
    - us-east-2
    - us-east-1
    - us-west-1
    - us-west-2
    - ap-south-1
    - ap-northeast-2
    - ap-southeast-1
    - ap-southeast-2
    - ap-northeast-1
    - ca-central-1
    - cn-north-1
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - eu-west-3
    - sa-east-1

  SdsAccountNumber:
    Description: AWS Account Number for the SDS that will be publishing messages to the ingest job topic
    Type: Number

  CachedCmrTokenBucket:
    Description: Name of S3 bucket where cached CMR authentication token is stored
    Type: String

  CachedCmrTokenKey:
    Description: S3 key where cached CMR authentication token is stored
    Type: String
    Default: cached-cmr-auth-token-test

  CmrTokenLambda:
    Description: Name of lambda function for fetching new CMR authentication tokens
    Type: String
    Default: cmr-token:TEST

  CmrGranuleUrl:
    Description: Base URL for the CMR Create/Update granule endpoint
    Type: String

  CmrConceptSearchUrl:
    Description: Base URL for the CMR concept search endpoint
    Type: String

  CmrClientId:
    Description: Value for Client-Id header included with CMR search requests
    Type: String

  IngestContainerImage:
    Description: Full URL path of the docker container image to use for ingest activities
    Type: String

  IngestEc2Timeout:
    Description: Duration of EC2 autoscaling lifecycle termination hook, in seconds
    Type: Number
    MinValue: 0
    Default: 300

  IngestActivityTimeout:
    Description: Timeout for step function ingest activity, in seconds
    Type: Number
    MinValue: 0
    Default: 600

  Maturity:
    Description: Value for MATURITY tag to be applied to all taggable resources
    Type: String
    Default: DEV
    AllowedValues:
      - TEST
      - PROD
      - DEV

Outputs:

  JobTopic:
    Description: Submit ingest jobs to this topic
    Value: !GetAtt MainStack.Outputs.JobTopic

  ErrorTopic:
    Description: Subscribe to this topic to receive a notification when one or more ingest jobs fail
    Value: !GetAtt MainStack.Outputs.ErrorTopic

  NewSceneTopic:
    Description: Subscribe to this topic to receive a notification when new scenes are ingested
    Value: !GetAtt MainStack.Outputs.NewSceneTopic

Resources:

  MainStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
        - Key: MATURITY
          Value: !Ref Maturity
        - Key: APPLICATION
          Value: GRFN-INGEST
      Parameters:
        Name: !Ref AWS::StackName
        LogLevel: !Ref LogLevel
        VpcId: !Ref VpcId
        SubnetId: !Join [",", !Ref SubnetId]
        PrivateBucket: !Ref PrivateBucket
        PublicBucket: !Ref PublicBucket
        DistributionBaseUrl: !Ref DistributionBaseUrl
        BrowseBaseUrl: !Ref BrowseBaseUrl
        CachedCmrTokenBucket: !Ref CachedCmrTokenBucket
        CachedCmrTokenKey: !Ref CachedCmrTokenKey
        CmrTokenLambda: !Ref CmrTokenLambda
        CmrGranuleUrl: !Ref CmrGranuleUrl
        CmrConceptSearchUrl: !Ref CmrConceptSearchUrl
        CmrClientId: !Ref CmrClientId
        DefaultResponseTopicArn: !Ref DefaultResponseTopicArn
        DefaultResponseTopicRegion: !Ref DefaultResponseTopicRegion
        IngestContainerImage: !Ref IngestContainerImage
        IngestEc2Timeout: !Ref IngestEc2Timeout
        IngestActivityTimeout: !Ref IngestActivityTimeout
        SdsAccountNumber: !Ref SdsAccountNumber
      TemplateURL: cloudformation-main.yaml
