AWSTemplateFormatVersion: 2010-09-09

Parameters:

  Name:
    Type: String

  PrivateBucket:
    Type: String

  PublicBucket:
    Type: String

  AuxBucket:
    Type: String

  DistributionBaseUrl:
    Type: String

  BrowseBaseUrl:
    Type: String

  ReformatApiUrl:
    Type: String

Outputs:

  LambdaArn:
    Value: !GetAtt Lambda.Arn

Resources:

  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${Name}-dlq"
      MessageRetentionPeriod: 1209600

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${Name}"
      RetentionInDays: 30

  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref Name
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Action: sts:AssumeRole
          Principal:
            Service: lambda.amazonaws.com
          Effect: Allow
      Policies:
      - PolicyName: policy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: !GetAtt LogGroup.Arn
          - Effect: Allow
            Action: sqs:SendMessage
            Resource: !GetAtt DeadLetterQueue.Arn
          - Effect: Allow
            Action: s3:GetObject
            Resource:
            - !Sub "arn:aws:s3:::${PrivateBucket}/*"
            - !Sub "arn:aws:s3:::${PublicBucket}/*"
            - !Sub "arn:aws:s3:::${AuxBucket}/*"
          - Effect: Allow
            Action: s3:PutObject
            Resource: !Sub "arn:aws:s3:::${AuxBucket}/*"

  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref Name
      Code: src/
      DeadLetterConfig:
        TargetArn: !GetAtt DeadLetterQueue.Arn
      Environment:
        Variables:
          CONFIG: !Sub |-
            {
              "output_bucket": "${AuxBucket}",
              "api_url": "${ReformatApiUrl}",
              "granule_data": {
                "download_path": "${DistributionBaseUrl}/{0}",
                "browse_path": "${BrowseBaseUrl}/{0}",
                "missions": [
                  {"name": "S1 I-grams (BETA) - Kilauea Volcano, HI", "coords": [[-159,16],[-150,16],[-150,23],[-159,23]]},
                  {"name": "S1 I-grams (BETA) - Northern CA", "coords": [[-126,38.4],[-116,38.4],[-116,42],[-126,42]]},
                  {"name": "S1 I-grams (BETA) - Central CA", "coords": [[-126,37],[-116,37],[-116,38.4],[-126,38.4]]},
                  {"name": "S1 I-grams (BETA) - Southern CA", "coords": [[-123,30],[-114,30],[-114,37],[-123,37]]},
                  {"name": "S1 I-grams (BETA) - Other", "coords": [[-180,-90],[180,-90],[180,90],[-180,90]]}
                ],
                "collection": {
                  "dataset_id": "Sentinel-1 Interferograms (BETA)",
                  "processing_type_display": "Standard Product, NetCDF",
                  "processing_description": "Sentinel-1 SLC interferometric products generated by JPL using ISCE v2.0.0, delivered by ASF"
                }
              },
              "derived_products": [
                {
                  "label": "unwrappedPhase",
                  "layer": "science/grids/data/unwrappedPhase",
                  "dataset_id": "Sentinel-1 Interferograms - Unwrapped Phase (BETA)",
                  "processing_type_display": "Unwrapped Phase, GeoTIFF",
                  "processing_description": "Sentinel-1 SLC interferometric products generated by JPL using ISCE v2.0.0, delivered by ASF"
                },
                {
                  "label": "coherence",
                  "layer": "science/grids/data/coherence",
                  "dataset_id": "Sentinel-1 Interferograms - Coherence (BETA)",
                  "processing_type_display": "Coherence, GeoTIFF",
                  "processing_description": "Sentinel-1 SLC interferometric products generated by JPL using ISCE v2.0.0, delivered by ASF"
                },
                {
                  "label": "amplitude",
                  "layer": "science/grids/data/amplitude",
                  "dataset_id": "Sentinel-1 Interferograms - Amplitude (BETA)",
                  "processing_type_display": "Amplitude, GeoTIFF",
                  "processing_description": "Sentinel-1 SLC interferometric products generated by JPL using ISCE v2.0.0, delivered by ASF"
                },
                {
                  "label": "connectedComponents",
                  "layer": "science/grids/data/connectedComponents",
                  "dataset_id": "Sentinel-1 Interferograms - Connected Components (BETA)",
                  "processing_type_display": "Connected Components, GeoTIFF",
                  "processing_description": "Sentinel-1 SLC interferometric products generated by JPL using ISCE v2.0.0, delivered by ASF"
                }
              ]
            }
      Handler: main.lambda_handler
      MemorySize: 128
      Role: !GetAtt Role.Arn
      Runtime: python2.7
      Timeout: 60
