AWSTemplateFormatVersion: 2010-09-09

Parameters:

  Name:
    Type: String

  VerifyLambdaArn:
    Type: String

  IngestLambdaArn:
    Type: String

  NotifyLambdaArn:
    Type: String

  Echo10ConstructionLambdaArn:
    Type: String

Outputs:

  StepFunctionArn:
    Value: !Ref StepFunction

  CmrActivityArn:
    Value: !Ref CmrActivity

Resources:

  CmrActivity:
    Type: AWS::StepFunctions::Activity
    Properties:
      Name: !Sub "${Name}-echo10-to-cmr"

  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Name}-step-function"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Action: sts:AssumeRole
          Principal:
            Service: states.amazonaws.com
          Effect: Allow
      Policies:
      - PolicyName: policy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action: lambda:InvokeFunction
            Resource:
            - !Ref VerifyLambdaArn
            - !Ref NotifyLambdaArn
            - !Ref Echo10ConstructionLambdaArn

  StepFunction:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Ref Name
      RoleArn: !GetAtt Role.Arn
      DefinitionString: !Sub |-
        {
          "Comment": "A step function to control lambdas for GRFN Ingest",
          "StartAt": "Verify",
          "States": {
            "Verify": {
              "Type": "Task",
              "Resource": "${VerifyLambdaArn}",
              "Next": "Ingest",
              "ResultPath": "$.VerifyResults",
              "Retry": [
                {
                  "ErrorEquals": ["INVALID_MESSAGE", "INVALID_METADATA"],
                  "MaxAttempts": 0
                },
                {
                  "ErrorEquals": ["States.ALL"]
                }
              ],
              "Catch": [{
                "ErrorEquals": ["States.ALL"],
                "Next": "Notify",
                "ResultPath": "$.Error"
              }]
            },
            "Ingest": {
              "Type": "Task",
              "Resource": "${IngestLambdaArn}",
              "ResultPath": "$.IngestResults",
              "Next": "Echo10Construction",
              "Retry": [{
                "ErrorEquals": ["States.ALL"]
              }],
              "Catch": [{
                "ErrorEquals": ["States.ALL"],
                "Next": "Notify",
                "ResultPath": "$.Error"
              }]
            },
            "Echo10Construction": {
              "Type": "Task",
              "Resource": "${Echo10ConstructionLambdaArn}",
              "InputPath": "$.IngestResults",
              "ResultPath": "$.ConstructionResults",
              "Next": "Echo10ToCMR",
              "Retry": [{
                "ErrorEquals": ["States.ALL"]
              }],
              "Catch": [{
                "ErrorEquals": ["States.ALL"],
                "Next": "Notify",
                "ResultPath": "$.Error"
              }]
            },
            "Echo10ToCMR": {
              "Type": "Task",
              "Resource": "${CmrActivity}",
              "TimeoutSeconds": 30,
              "InputPath": "$.ConstructionResults",
              "ResultPath": "$.CmrResults",
              "Next": "Notify",
              "Retry": [{
                "ErrorEquals": ["States.ALL"],
                "MaxAttempts": 7,
                "BackoffRate": 5
              }],
              "Catch": [{
                "ErrorEquals": ["States.ALL"],
                "Next": "Notify",
                "ResultPath": "$.Error"
              }]
            },
            "Notify": {
              "Type": "Task",
              "Resource": "${NotifyLambdaArn}",
              "ResultPath": "$.NotifyResults",
              "Retry": [{
                "ErrorEquals": ["States.ALL"]
              }],
              "Next": "Check_Status"
            },
            "Check_Status": {
              "Type" : "Choice",
              "Choices": [{
                "Variable": "$.NotifyResults.Status",
                "StringEquals": "success",
                "Next": "Success"
              }],
              "Default": "Failure"
            },
            "Failure": {
              "Type": "Fail",
              "Error": "Ingest failed.",
              "Cause": "Ingest failed.  Inspect the 'Error' field of the Failure task's input for details."
            },
            "Success": {
              "Type": "Pass",
              "End": true
            }
          }
        }
