AWSTemplateFormatVersion: 2010-09-09

Parameters:

  Name:
    Type: String

  VerifyLambdaArn:
    Type: String

  IngestLambdaArn:
    Type: String

  Echo10ConstructionLambdaArn:
    Type: String

Outputs:

  StepFunctionArn:
    Value: !Ref StepFunction

  CmrActivityArn:
    Value: !Ref CmrActivity

Resources:

  CmrActivity:
    Type: AWS::StepFunctions::Activity
    Properties:
      Name: !Sub "${Name}-echo10-to-cmr"

  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Name}-step-function"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Action: sts:AssumeRole
          Principal:
            Service: states.amazonaws.com
          Effect: Allow
      Policies:
      - PolicyName: policy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action: lambda:InvokeFunction
            Resource:
            - !Ref VerifyLambdaArn
            - !Ref IngestLambdaArn
            - !Ref Echo10ConstructionLambdaArn

  StepFunction:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Ref Name
      RoleArn: !GetAtt Role.Arn
      DefinitionS3Location: step-function.json
      DefinitionSubstitutions:
        VerifyLambdaArn: !Ref VerifyLambdaArn
        IngestLambdaArn: !Ref IngestLambdaArn
        Echo10ConstructionLambdaArn: !Ref Echo10ConstructionLambdaArn
        CmrActivity: !Ref CmrActivity
