FROM python:slim
MAINTAINER Alaska Satellite Facility

ENTRYPOINT ["python","/usr/local/sbin/daemon.py"]

COPY requirements.txt /usr/local/etc/requirements.txt
COPY src/* /usr/local/sbin/

RUN apt-get update && \
    pip install -r /usr/local/etc/requirements.txt
