AWSTemplateFormatVersion: 2010-09-09

Parameters:

  Name:
    Type: String

  TokenBucket:
    Type: String

  TokenKey:
    Type: String

  CertificateSecretArn:
    Type: String

Outputs:

  LambdaName:
    Value: !Ref Lambda

Resources:

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${Name}"
      RetentionInDays: 30

  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref Name
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Action: sts:AssumeRole
          Principal:
            Service: lambda.amazonaws.com
          Effect: Allow
      Policies:
      - PolicyName: policy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: !GetAtt LogGroup.Arn
          - Effect: Allow
            Action: secretsmanager:GetSecretValue
            Resource: !Ref CertificateSecretArn
          - Effect: Allow
            Action: s3:PutObject
            Resource: !Sub "arn:aws:s3:::${TokenBucket}/${TokenKey}"

  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref Name
      Code: src/
      Environment:
        Variables:
          CERTIFICATE_SECRET_ARN: !Ref CertificateSecretArn
          BUCKET: !Ref TokenBucket
          KEY: !Ref TokenKey
      Handler: cmr_token.lambda_handler
      MemorySize: 128
      Role: !GetAtt Role.Arn
      Runtime: python3.12
      Timeout: 60
