name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  call-release-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-release.yml@v0.9.0
    with:
      release_prefix: GRFN Ingest
      release_branch: prod
      develop_branch: test
    secrets:
      USER_TOKEN: ${{ secrets.TOOLS_BOT_PAK }}
