name: Create Release Comment

on:
  pull_request:
    types:
      - opened
    branches:
      - prod

jobs:
  call-release-workflow:
    # Docs: https://github.com/ASFHyP3/actions
    uses: ASFHyP3/actions/.github/workflows/reusable-release-checklist-comment.yml@v0.7.1
    secrets:
      USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
