name: Static code analysis

on: push

jobs:

  flake8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 flake8-import-order flake8-builtins  # FIXME add flake8-blind-except
      - run: flake8 --max-line-length=120 --import-order-style=pycharm --statistics --application-import-names echo10_construction verify

  cfn-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: scottbrenner/cfn-lint-action@v2
        with:
          command: cfn-lint --info --ignore-checks W3002 --template **/cloudformation.yaml

  statelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: gem install statelint
      - run: |
          # replace DefinitionSubstitution placeholders with dummy URIs to suppress linter errors
          sed -i 's/"Resource": "${.*}"/"Resource": "foo:bar"/' step-function/step-function.json
          statelint step-function/step-function.json
