version: 0.1

environment_variables:
  plaintext:
   PIPELINE_NAME: "custom-metrics-test"
   BUCKET: "grfn-software"
   PREFIX: "lambda"

phases:
  pre_build:
    commands:
      - aws codepipeline get-pipeline-state --name $PIPELINE_NAME --query 'stageStates[*].actionStates[?actionName==`Source`].currentRevision.revisionId' --output text | cut -c1-7 > sha1.txt
      - sed -i "s/\$SHA1/$(cat sha1.txt)/" cloudformation.yaml
  build:
    commands:
      - pip install -r requirements.txt -t src/
      - aws cloudformation package --template-file cloudformation.yaml --s3-bucket $BUCKET --s3-prefix $PREFIX --output-template-file cloudformation-final.yaml

artifacts:
  type: zip
  files:
    - cloudformation-final.yaml
